apiVersion: apps/v1
kind: Deployment
metadata:
  name: ems
  labels:
    app: ems
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ems
  volumes:
       - name: test-ems-storage
         persistentVolumeClaim:
          claimName: pet-pvc    
  template:
    metadata:
      labels:
        app: ems
    spec:
      containers:
        - name: ems
          image: 'artifactory:5000/doq/ems:latest'
          ports:
            - containerPort: 8080
              protocol: TCP
          volumeMounts:
           - name: test-ems-storage
             mountPath: /
  

---

apiVersion: v1
kind: Service
metadata:
  labels:
    app: ems
    app.kubernetes.io/instance: ems
  name: ems
spec:
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: ems
  sessionAffinity: None
  type: ClusterIP

---

apiVersion: route.openshift.io/v1
kind: Route
metadata:
  annotations:
    openshift.io/host.generated: "true"
  labels:
    app: ems
    app.kubernetes.io/instance: ems
  name: ems
spec:
  host: ems-dso-pl-testing.ca
  port:
    targetPort: 8080
  to:
    kind: Service
    name: ems
    weight: 100
  wildcardPolicy: None
